### ISSUE TITLE
What date range do the results cover?

### ISSUE THREAD

**Issue by netievalage** [FlipsiderEfer/Ethereum-Early-Adopters#1]
Hello, thanks for the work. What date range do your study results cover?

**Comment by BLSChain** [comment]
2019

**Comment by eferbarn** [comment]
> Hello, thanks for the work. What date range do your study results cover?

Hi there,
From **_2015-08-08T05:20:23.000Z_** (The deployment datetime of the first contracts in the row) to **_2023-11-28T09:40:59.000Z_** (The deployment datetime of the last contract).
